//! Error type for the node module.
use thiserror::Error;

/// Errors generated by the node module.
#[derive(Debug, Error)]
pub enum Error {
    /// Error generated by the client.
    #[error(transparent)]
    Client(#[from] crate::client::Error),

    /// Error generated by the server.
    #[error(transparent)]
    Server(#[from] crate::server::Error),
}
