use thiserror::Error;

/// Errors generated by the library.
#[derive(Debug, Error)]
pub enum Error {
    /// Error generated when a system message is not found.
    #[error("no system message for key '{0}'")]
    NoSysMessage(String),
}
