[package]
name = "sos-core"
version = "0.1.0"
edition = "2021"

[dependencies]
async-trait = "0.1"
aes-gcm = { version = "0.9", features = ["std"] }
chacha20poly1305 = { version = "0.9", features = ["std"] }
rand = "0.8"
thiserror = "1"
web3-signature = { version = "0.2.3", features = ["single-party"] }
serde = { version = "1", features = ["derive"] }
hex = { version = "0.4", features = ["serde"] }
serde_json = "1"
k256 = { version = "0.10", features = ["ecdsa", "sha256", "keccak256"] }
subtle = "2.4"
jwt-simple = "0.10.8"
zeroize = "1.4"
argon2 = { version = "0.4", features = ["std"]}
# matches the version in k256
sha3 = "0.9"
# Note using an old version of `rand` (0.6) due to bip39 dependency
# SEE: https://github.com/rust-bitcoin/rust-bip39/issues/14
bip39 = { version =  "1", features = ["std", "rand"] }
uuid = { version = "0.8", features = ["serde", "v4"] }
url = { version = "2.2", features = ["serde"] }
serde-binary  = "0.3.2"
chrono = { version = "0.4", features = ["serde"] }

[target.'cfg(target_arch = "wasm32")'.dependencies]
getrandom = {version = "0.2", features = ["js"]}
uuid = { version = "0.8", features = ["serde", "v4", "wasm-bindgen"] }

#[dependencies.binary_rw]
#version = "2"
#path = "../../../forks/binary-rs"
#features = ["wasm32"]

[dependencies.chbs]
version = "0.1"
git = "https://gitlab.com/tmpfs/chbs.git"
branch = "wasm32"

[dev-dependencies]
anyhow = "1"
