[package]
name = "sos-core"
version = "0.1.0"
edition = "2021"

[dependencies]
aes-gcm = { version = "0.9", features = ["std"] }
rand = "0.8"
anyhow = "1"
serde = { version = "1", features = ["derive"] }
hex = { version = "0.4", features = ["serde"] }
serde_json = "1"
k256 = { version = "0.10", features = ["ecdsa", "sha256", "keccak256"] }
subtle = "2.4"
jwt-simple = "0.10.8"
zeroize = "1.4"
# matches the version in k256
sha3 = "0.9"
# Note using an old version of `rand` (0.6) due to bip39 dependency
# SEE: https://github.com/rust-bitcoin/rust-bip39/issues/14
bip39 = { version =  "1", features = ["std", "rand"] }
uuid = { version = "0.8", features = ["serde", "v4"] }

[dependencies.binary_rw]
version = "1.3.2"
git = "https://github.com/tmpfs/binary-rs.git"
branch = "from-vec"
