[package]
name = "sos-core"
version = "0.1.0"
edition = "2021"
description = "Distributed, encrypted database for private secrets."
homepage = "https://saveoursecrets.com"
license = "GPL-3.0"

[lib]
crate-type = ["cdylib", "rlib"]

[dependencies]
async-trait = "0.1"
aes-gcm = { version = "0.9", features = ["std"] }
chacha20poly1305 = { version = "0.10.1", features = ["std"] }
tracing = "0.1"
filetime = "0.2"
rand = "0.8"
thiserror = "1"
web3-signature = { version = "0.2.6", features = ["single-party"] }
web3-address = { version = "0.4.1", features = ["ethereum"] }
serde = { version = "1", features = ["derive"] }
hex = { version = "0.4", features = ["serde"] }
serde_json = "1"
k256 = { version = "0.11", features = ["ecdsa", "ecdh", "sha256", "keccak256"] }
subtle = "2.4"
zeroize = { version = "1.4", features = ["zeroize_derive"] }
argon2 = { version = "0.4", features = ["std"]}
# matches the version in k256
sha3 = "0.10"
uuid = { version = "1", features = ["serde", "v4"] }
url = { version = "2.2", features = ["serde"] }
bitflags = "1"
ouroboros = "0.15"
pem = { version = "1.1.0", features = ["serde"] }
secrecy = { version = "0.8", features = ["serde"] }
tempfile = "3"
log = "0.4"
http = "0.2"
passwords = "3"
totp-sos = { version = "3", features = ["serde"] }
vcard4 = { version = "0.1.4", features = ["serde"] }
parking_lot = "0.12"
urn = "0.5"

binary-stream = { version = "3.3.2", features = ["32bit"] }

tar = { version = "0.4", default-features = false }
flate2 = "1"

time = { version = "0.3", features = ["serde", "local-offset", "formatting", "wasm-bindgen"] }

unicode-segmentation = "1.10"

[dependencies.probly-search]
version = "2.0.0-alpha-2"
#path = "../../../../forks/probly-search"
git = "https://github.com/tmpfs/probly-search/"
branch = "multi-field"

[target.'cfg(not(target_arch = "wasm32"))'.dependencies]
file-guard = "0.1"
tokio = { version = "1", default-features = false, features = ["fs", "io-util"] }

[target.'cfg(target_arch = "wasm32")'.dependencies]
getrandom = {version = "0.2", features = ["js"]}
uuid = { version = "1", features = ["serde", "v4", "js"] }
tokio = { version = "1", default-features = false, features = ["rt"] }

[dependencies.rs_merkle]
version = "1.2"
#path = "../../../../forks/rs-merkle"


[dependencies.chbs]
version = "0.1.1"
#git = "https://gitlab.com/timvisee/chbs.git"
#rev = "1bb19733ac66cebf58b726d14770a616faba85dd"
#branch = "wasm32"

[dev-dependencies]
anyhow = "1"

[package.metadata.release]
tag = false
shared-version = true
