/*
 Generated by typeshare 1.12.0
*/

/** IPC request information. */
export type IpcRequestBody = 
	/** Query app status. */
	| { kind: "status", body?: undefined }
	/** Ping the server. */
	| { kind: "ping", body?: undefined }
	/** Request to open a URL. */
	| { kind: "openUrl", body: string }
	/** Request the accounts list. */
	| { kind: "listAccounts", body?: undefined }
	/** Request authentication for an account. */
	| { kind: "authenticate", body: {
	/** Account address. */
	address: string;
}}
	/** Request to lock an account. */
	| { kind: "lock", body: {
	/** Account address. */
	address?: string;
}}
	/** Request to search the index. */
	| { kind: "search", body: {
	/** Query needle. */
	needle: string;
	/** Query filter. */
	filter: QueryFilter;
}}
	/** Request to query views in the search index. */
	| { kind: "queryView", body: {
	/** Document views. */
	views: DocumentView[];
	/** Archive filter. */
	archive_filter?: ArchiveFilter;
}};

/** IPC request information. */
export interface IpcRequest {
	/** Request identifier. */
	id: number;
	/** Request payload. */
	payload: IpcRequestBody;
}

/** IPC response error. */
export interface IpcResponseError {
	/** Error code. */
	code: number;
	/** Error message. */
	message: string;
}

/** Generic command outcome. */
export enum CommandOutcome {
	/** Account not found. */
	NotFound = "notFound",
	/** Already authenticated. */
	AlreadyAuthenticated = "alreadyAuthenticated",
	/** Not authenticated. */
	NotAuthenticated = "notAuthenticated",
	/** Account was authenticated. */
	Success = "success",
	/** Authentication failed. */
	Failed = "failed",
	/** User canceled. */
	Canceled = "canceled",
	/** Timed out waiting for user input. */
	TimedOut = "timedOut",
	/** Too many attempts to authenticate. */
	Exhausted = "exhausted",
	/** Error attempting to get user input. */
	InputError = "inputError",
}

/** IPC response body. */
export type IpcResponseBody = 
	/** Status information. */
	| { kind: "status", body: {
	/**
	 * Whether the app is running as determined
	 * by an active account file lock.
	 */
	app: boolean;
	/** Whether the IPC channel is responding to a ping. */
	ipc: boolean;
}}
	/** Reply to a ping. */
	| { kind: "pong", body?: undefined }
	/** Result of opening a URL. */
	| { kind: "openUrl", body: boolean }
	/** List of accounts. */
	| { kind: "accounts", body: AccountsList }
	/** Authenticate response. */
	| { kind: "authenticate", body: CommandOutcome }
	/** Lock response. */
	| { kind: "lock", body: CommandOutcome }
	/** Search query response. */
	| { kind: "search", body: SearchResults }
	/** Query view response. */
	| { kind: "queryView", body: SearchResults };

