//! Error type for the library.
use thiserror::Error;

/// Error type for the migration library.
#[derive(Debug, Error)]
pub enum Error {
    /// Error generated by the core library.
    #[error(transparent)]
    Core(#[from] sos_core::Error),

    /// Error generated by the keychain access integration.
    #[cfg(target_os = "macos")]
    #[error(transparent)]
    Keychain(#[from] crate::import::keychain::Error),
}
