#![deny(missing_docs)]
//! Migration import and export that exposes secrets
//! unencrypted.
//!
//! Used to move from or to another service provider or
//! software application.
use thiserror::Error;

/// Error type for the migration library.
#[derive(Debug, Error)]
pub enum Error {

    /// Error generated if the name for a keychain could not be determined, no file stem.
    #[error("could not determine name for a keychain")]
    NoKeychainName,
    
    /// Error generated by the io library.
    #[error(transparent)]
    Io(#[from] std::io::Error),
    
    /// Error generated by the security framework.
    #[cfg(target_os = "macos")]
    #[error(transparent)]
    SecurityFramework(#[from] security_framework::base::Error),

    /// Error generated by the mpsc sender.
    #[error(transparent)]
    SendBool(#[from] std::sync::mpsc::SendError<bool>),
}

/// Result type for the migration library.
pub type Result<T> = std::result::Result<T, Error>;

pub mod export;
pub mod import;
