gui = true

[audit]
file = "audit.dat"

[api]
origins = [
  "http://localhost:5053",
  "http://localhost:8080",
  "http://localhost:8000",
]

[tls]
cert = "cert.pem"
key = "key.pem"

[storage]
url = "file://."
