key = "./server_identity.pem"

[audit]
file = "audit.dat"

[cors]
origins = [
  "http://localhost:5053",
  "http://localhost:8080",
  "http://localhost:8000",

  "https://localhost:5053",
  "https://localhost:8080",
]

#[tls]
#cert = "cert.pem"
#key = "key.pem"

[storage]
url = "file://./accounts"
