[package]
name = "sos-ipc"
version = "0.16.0"
edition = "2021"
description = "Inter-process communication for the Save Our Secrets SDK."
homepage = "https://saveoursecrets.com"
license = "MIT OR Apache-2.0"
repository = "https://github.com/saveoursecrets/sdk"

[features]
default = ["local-socket"]
tcp = []
local-socket = ["interprocess"]
native-bridge = ["open", "once_cell"]
native-send = ["tokio/process"]

[dependencies]
thiserror.workspace = true
prost.workspace = true
tracing.workspace = true
async-trait.workspace = true
serde.workspace = true
serde_json.workspace = true
typeshare.workspace = true
parking_lot.workspace = true

sos-net = { version = "0.16", path = "../net", features = ["account", "search"] }
sos-account-extras = { version = "0.16", path = "../account_extras/", features = ["clipboard"] }

tokio = { version = "1", features = ["rt", "rt-multi-thread", "net", "macros", "io-util", "io-std", "sync"] }
tokio-stream = "0.1"
tokio-util = { version = "0.7", features = ["codec"] }
futures-util = { version = "0.3", features = ["sink"] }
interprocess = { version = "2", features = ["tokio"], optional = true }

open = { version = "5", optional = true }
once_cell = { workspace = true, optional = true }

# HTTP dependencies for local server
http.workspace = true
tower = { version = "0.5", features = ["util"]}
hyper = { version = "1", features = ["http1", "server"] }
matchit = "0.7"

[build-dependencies]
rustc_version = "0.4.1"
prost-build = "0.13"
protoc-bin-vendored = "3"

