[package]
name = "sos-ipc"
version = "0.16.0"
edition = "2021"
description = "Inter-process communication for the Save Our Secrets SDK."
homepage = "https://saveoursecrets.com"
license = "MIT OR Apache-2.0"
repository = "https://github.com/saveoursecrets/sdk"

[features]
client = [
  "hyper/http1",
  "hyper/client",
  "http-body-util",
  "hyper-util",
]
server = [
  "hyper/http1",
  "hyper/server",
  "tower",
  "matchit",
  "http-body-util",
  "hyper-util",
]
native-bridge-server = ["client","open", "once_cell"]
native-bridge-client = ["tokio/process", "tokio/io-std"]

[dependencies]
thiserror.workspace = true
tracing.workspace = true
serde.workspace = true
serde_json.workspace = true
typeshare.workspace = true
parking_lot.workspace = true
http.workspace = true
bytes.workspace = true

sos-sdk = { version = "0.16", path = "../sdk", features = ["account"] }
sos-protocol = { version = "0.16", path = "../protocol" }

tokio = { version = "1", features = ["io-util", "sync"] }
tokio-util = { version = "0.7", features = ["codec"] }
futures-util = { version = "0.3", features = ["sink"] }
interprocess = { version = "2", features = ["tokio"] }

# server and client
hyper = { version = "1", optional = true }
http-body-util = { version = "0.1", optional = true }
hyper-util = { version = "0.1", features = ["tokio"], optional = true }

# server
tower = { version = "0.5", features = ["util"], optional = true }
matchit = { version = "0.7", optional = true }

# native bridge
open = { version = "5", optional = true }
once_cell = { workspace = true, optional = true }

[build-dependencies]
rustc_version = "0.4.1"

