[package]
name = "sos-migrate"
version = "0.5.0"
edition = "2021"

[dependencies]
sos-sdk = { path = "../sdk", version = "0.5" }
thiserror = "1"
secrecy = { version = "0.8", features = ["serde"] }
serde = { version = "1", features = ["derive"] }
serde_json = "1"
hex = { version = "0.4", features = ["serde"] }
dirs = "4"
url = { version = "2", features = ["serde"] }
parking_lot = "0.12"
vcard4 = { version = "0.4.4", features = ["serde"] }
time = { version = "0.3.19", features = ["serde-human-readable", "local-offset", "wasm-bindgen"] }
async-trait = "0.1"
tokio = { version = "1", default-features = false, features = ["sync"] }
async_zip = { version = "0.0.15", default-features = false, features = ["deflate", "tokio"] }
tokio-util = { version = "0.7", default-features = false, features = ["compat"] }
futures-util = "0.3"
futures = "0.3"
csv-async = { version = "1", features = ["tokio", "with_serde"] }

[target.'cfg(target_os="macos")'.dependencies]
security-framework = "2.8"
logos = "0.12"
plist = "1"

[dev-dependencies]
sos-sdk = { path = "../sdk", version = "0.5", features = ["test-utils"] }
anyhow = "1"
tokio = { version = "1", default-features = false, features = ["rt", "macros"] }

[features]
interactive-keychain-tests = []

[build-dependencies]
rustc_version = "0.4.0"

[package.metadata.release]
tag = false
shared-version = true

[package.metadata.docs.rs]
all-features = true
