[package]
name = "sos-migrate"
version = "0.1.0"
edition = "2021"

[dependencies]
sos-core = { path = "../core", version = "0.1.0" }
thiserror = "1"
secrecy = { version = "0.8", features = ["serde"] }
serde = { version = "1", features = ["derive"] }
tar = { version = "0.4", default-features = false }
serde_json = "1"
hex = { version = "0.4", features = ["serde"] }
dirs = "4"

[target.'cfg(target_os="macos")'.dependencies]
security-framework = "2.8"

[dev-dependencies]
sos-core = { path = "../core", version = "0.1.0", features = ["test-utils"] }
anyhow = "1"

[package.metadata.release]
tag = false
shared-version = true
