//! Extra functions for local accounts in the [SDK](https://docs.rs/sos-sdk) for [Save Our Secrets](https://saveoursecrets.com).
#![deny(missing_docs)]
#![forbid(unsafe_code)]
#![cfg_attr(all(doc, CHANNEL_NIGHTLY), feature(doc_auto_cfg))]

mod error;

/// Errors generated by the extras library.
pub use error::Error;

/// Result type for the extras library.
pub type Result<T> = std::result::Result<T, Error>;

#[cfg(feature = "preferences")]
pub mod preferences;

#[cfg(feature = "security-report")]
pub mod security_report;

#[cfg(feature = "system-messages")]
pub mod system_messages;

#[cfg(feature = "clipboard")]
pub mod clipboard;
