[package]
name = "sos-vfs"
version = "0.2.2"
edition = "2021"
description = "Virtual file system same as tokio::fs."
homepage = "https://saveoursecrets.com"
license = "MIT OR Apache-2.0"
repository = "https://github.com/saveoursecrets/sdk"

[features]
mem-fs = []

[target.'cfg(target_arch = "wasm32")'.dependencies]
tokio = { version = "1", default-features = false, features = ["rt", "sync"] }

[target.'cfg(not(target_arch = "wasm32"))'.dependencies]
tokio = { version = "1", default-features = false, features = ["rt", "fs", "sync", "io-util", "macros"] }

[dependencies]
futures = "0.3"
async-recursion = "1"
once_cell = "1"
parking_lot = "0.12"
bitflags = "1"

[dev-dependencies]
anyhow = "1"
