extend= [
  { path = "coverage.toml" }
]

[config]
default_to_workspace = false
skip_core_tasks = true

[env]
RUST_BACKTRACE = 0
BUILD_TARGET = "${CARGO_MAKE_RUST_TARGET_TRIPLE}"
# Increase time for integration tests as the CLI
# tests take a while due to so many exec calls
RUST_TEST_TIME_INTEGRATION = "120000,240000"

[tasks.fix-all]
workspace = true
command = "cargo"
args = ["fix", "--all-features", "--allow-dirty"]

[tasks.fix-clippy]
workspace = true
command = "cargo"
args = ["clippy", "--fix", "--all-features"]

[tasks.fix]
dependencies = ["fix-clippy", "fix-all", "format"]

[tasks.format]
workspace = true
command = "cargo"
args = ["fmt"]

[tasks.format-check]
command = "cargo"
args = ["fmt", "--all", "--", "--check"]

[tasks.check]
workspace = true
command = "cargo"
args = ["check"]

[tasks.clippy]
workspace = true
command = "cargo"
args = ["clippy", "--all-features"]

[tasks.clean]
workspace = true
command = "cargo"
args = ["clean"]

[tasks.build]
workspace = true
command = "cargo"
args = ["build"]
dependencies = ["clean"]

[tasks.release]
command = "cargo"
args = ["build", "--bins", "--all", "--release"]

[tasks.doc]
toolchain = "nightly"
command = "cargo"
args = [
  "doc",
  "--workspace",
  "--open",
  "--no-deps"
]

[tasks.unit]
command = "cargo"
args = ["test", "--all", "--lib"]

[tasks.test-audit-trail]
command = "cargo"
args = ["test", "audit"]

[tasks.test-backup-archive]
command = "cargo"
args = ["test", "backup_archive"]

[tasks.test-command-line]
command = "cargo"
args = ["test", "command_line", "--features", "enable-cli-tests", "--", "--nocapture"]
dependencies = ["clean-cli"]

[tasks.test-event-log]
command = "cargo"
args = ["test", "event_log_"]

[tasks.test-diff-merge]
command = "cargo"
args = ["test", "diff_merge_"]

[tasks.test-local-account]
command = "cargo"
args = ["test", "local_"]

[tasks.test-network-account]
command = "cargo"
args = ["test", "network_"]

[tasks.test-pairing]
command = "cargo"
args = ["test", "pairing_"]

[tasks.test-file-transfers]
command = "cargo"
args = ["test", "file_transfers_"]

[tasks.test-access-control]
command = "cargo"
args = ["test", "access_control_"]

[tasks.test-preferences]
command = "cargo"
args = ["test", "preferences_"]

[tasks.test-system-messages]
command = "cargo"
args = ["test", "system_messages_"]

[tasks.clean-cli]
script_runner = "@shell"
script = '''
rm -rf target/accounts
rm -f target/*.{zip,vcf,heic,txt,toml,csv,json}
'''

[tasks.test-cli]
script = { file = "./scripts/cli/specs.sh" }
dependencies = ["clean-cli"]

[tasks.test-shell]
script = { file = "./scripts/cli/shell.sh" }
dependencies = ["clean-cli"]

[tasks.demos]
script = { file = "./scripts/cli/demos.sh" }
dependencies = ["clean-cli"]

[tasks.test]
command = "cargo"
args = ["test", "--all", "--features", "enable-cli-tests"]
dependencies = ["clean-cli"]

[tasks.test-lite]
command = "cargo"
args = ["test", "--all"]
dependencies = ["clean-cli"]

[tasks.dev]
dependencies = ["check-wasm", "test", "format"]

[tasks.check-wasm-node-client]
command = "cargo"
args = [
  "check",
  "--target",
  "wasm32-unknown-unknown",
  "-p",
  "sos-net",
  "--no-default-features",
  "--features",
  "client"
]

[tasks.check-wasm]
command = "cargo"
args = ["check", "--target", "wasm32-unknown-unknown", "-p", "sos-sdk"]
dependencies = ["check-wasm-node-client"]

[tasks.dev-server]
script = '''
cargo run --bin sos-server -- start sandbox/config.toml
'''

[tasks.dev-certs]
script = '''
command -v mkcert && cd sandbox && 
  mkcert -key-file key.pem -cert-file cert.pem localhost 127.0.0.1 ::1
'''

[tasks.genhtml]
script = '''
grcov ${COVERAGE_PROF_OUTPUT} -s . --binary-path ./target/cover/debug -t html --branch --ignore-not-existing -o ./target/coverage/ --ignore 'workspace/*/build.rs' --ignore 'tests/*' --ignore 'target/*'

#genhtml -o ./target/debug/coverage/ --show-details --highlight --ignore-errors source --legend ./target/lcov.info
'''

[tasks.coverage]
alias = "coverage_grcov"
dependencies = ["clean-profraw"]

[tasks.clean-profraw]
script = '''
rm -f *.profraw
rm -f workspace/net/*.profraw
rm -f workspace/migrate/*.profraw
rm -f workspace/sdk/*.profraw
'''

[tasks.clean-coverage]
command = "cargo"
args = ["clean", "--target-dir", "target/coverage"]

[tasks.clean-cover]
command = "cargo"
args = ["clean", "--target-dir", "target/cover"]

[tasks.cover]
dependencies = [
  "clean-cli",
  "clean-cover",
  "clean-coverage",
  "coverage",
  "genhtml",
  "clean-profraw"
]
