use thiserror::Error;

/// Error type for the clipboard library.
#[derive(Debug, Error)]
pub enum Error {
    /// Error generated by the desktop clipboard library.
    #[cfg(all(not(target_os = "android"), not(target_os = "ios")))]
    #[error(transparent)]
    ArBoard(#[from] arboard::Error),
}
