use thiserror::Error;

/// Error type for the clipboard library.
#[derive(Debug, Error)]
pub enum Error {
    /// Error generated by the desktop clipboard library.
    #[error(transparent)]
    ArBoard(#[from] arboard::Error),
}
