//! Cross-platform keyboard with extra features to time out
//! sensitive data and listen for clipboard change events.
#![deny(missing_docs)]
#![forbid(unsafe_code)]
#![cfg_attr(all(doc, CHANNEL_NIGHTLY), feature(doc_auto_cfg))]

mod error;

/// Errors generated by the clipboard library.
pub use error::Error;

/// Result type for the clipboard library.
pub type Result<T> = std::result::Result<T, Error>;

mod clipboard;

pub use clipboard::*;
