//! Error for the agent key server.
use thiserror::Error;

/// Errors generated by the agent module.
#[derive(Debug, Error)]
pub enum Error {
    /// Error generated attempting so call send on a client before
    /// a connection has been established.
    #[error("agent client is not connected")]
    NotConnected,

    /// Error generated decoding an invalid message kind.
    #[error("message kind {0} is invalid")]
    InvalidMessageKind(u8),

    /// Error generated by the core library.
    #[error(transparent)]
    Core(#[from] sos_core::Error),

    /// Error generated by the standard io library.
    #[error(transparent)]
    Io(#[from] std::io::Error),

    /// Error generated by the binary stream library.
    #[error(transparent)]
    Binary(#[from] binary_stream::BinaryError),
}
