[package]
name = "sos-readline"
version = "0.1.0"
edition = "2021"
description = "Utilities for reading from stdin"
publish = false

[dependencies]
thiserror = "1"
rustyline = "10"
rustyline-derive = "0.7"
unicode-width = "0.1"
atty = "0.2"
secrecy = "0.8"

[package.metadata.release]
release = false
shared-version = true
