//! Error type for the peer library.
use thiserror::Error;

/// Errors generated by the peer library.
#[derive(Debug, Error)]
pub enum Error {
    /// Error generated when listening fails.
    #[error("listen {0} failed: {1}")]
    ListenFailed(String, String),

    /// Error generated when dialing fails.
    #[error("dial {0} failed")]
    DialFailed(String),

    /// Error generated when an error occurs on an outbound connection.
    #[error("outgoing connection error: {0}")]
    OutgoingConnection(String),

    /// Error generated attempting to parse a socket address.
    #[error(transparent)]
    AddrParse(#[from] std::net::AddrParseError),

    /// Error generated when by the hex library.
    #[error(transparent)]
    Hex(#[from] hex::FromHexError),

    /// Error generated when by the noise library.
    #[error(transparent)]
    Noise(#[from] libp2p::noise::NoiseError),

    /// Error generated when by decoding an identity keypair.
    #[error(transparent)]
    IdentityDecoding(#[from] libp2p::identity::DecodingError),

    /// Error generated when by the futures mpsc sender.
    #[error(transparent)]
    FutureMpscSend(#[from] futures::channel::mpsc::SendError),

    /// Error generated when by the futures oneshot.
    #[error(transparent)]
    FutureOneshotCancel(#[from] futures::channel::oneshot::Canceled),
}
