[package]
name = "sos-server"
version = "0.1.0"
edition = "2021"
default-run = "sos3-server"

[dependencies]
thiserror = "1"
sos-core = { path = "../core" }
clap = { version = "3", features = ["derive"] }
axum = { version = "0.5", features = ["headers"] }
axum-macros = "0.2"
hyper = { version = "0.14", features = ["full"] }
tokio = { version = "1", features = ["full"] }
tower = "0.4"
tower-http = { version = "0.2", features = ["full"] }
tracing = "0.1"
tracing-subscriber = { version = "0.3", features = ["env-filter"] }
serde = { version = "1", features = ["derive"] }
serde_json = "1"
uuid = { version = "0.8", features = ["serde", "v4"] }
async-trait = "0.1"
rust-embed = "6"
mime_guess = "2"
toml = "0.5"
url = { version = "2", features = ["serde"] }
base64 = "0.13"
sha3 = "0.10"

[features]
default = ["gui"]
gui = []

[[bin]]
name = "sos3-server"
path = "src/bin/main.rs"
