[package]
name = "sos-server"
version = "0.1.0"
edition = "2021"
default-run = "sos-server"
publish = false

[dependencies]
sos-core = { path = "../core", version = "0.1.0" }
sos-node = { path = "../node", version = "0.1.0", default-features = false, features = ["server", "gui"] }

clap = { version = "3", features = ["derive", "wrap_help"] }
tokio = { version = "1", features = ["full"] }
axum-server = { version = "0.4", features = ["tls-rustls"] }
tracing = "0.1"
tracing-subscriber = { version = "0.3", features = ["env-filter"] }

[[bin]]
name = "sos-server"
path = "src/bin/main.rs"

[package.metadata.release]
release = false
shared-version = true
