[package]
name = "sos3-server"
version = "0.1.0"
edition = "2021"
default-run = "sos3"

[dependencies]
anyhow = "1"
thiserror = "1"
sos-core = { path = "../core" }
clap = { version = "3", features = ["derive"] }
axum = "0.4"
axum-macros = "0.1"
hyper = { version = "0.14", features = ["full"] }
tokio = { version = "1", features = ["full"] }
tower = "0.4"
tracing = "0.1"
tracing-subscriber = { version = "0.3", features = ["env-filter"] }
serde = { version = "1", features = ["derive"] }
serde_json = "1"
uuid = { version = "0.8", features = ["serde", "v4"] }
async-trait = "0.1"
rust-embed = "6"
mime_guess = "2"

[features]
default = ["gui"]
gui = []

[[bin]]
name = "sos3"
path = "src/bin/main.rs"
