use std::path::PathBuf;
use thiserror::Error;

/// Errors generated creating and importing backup archives,
#[derive(Debug, Error)]
pub enum Error {
    /// Archive file already exists.
    #[error("archive file '{0}' already exists")]
    ArchiveFileExists(PathBuf),

    /// Errors generated by the database library.
    #[error(transparent)]
    Database(#[from] crate::Error),

    /// Errors generated by the IO module.
    #[error(transparent)]
    Io(#[from] std::io::Error),

    /// Error generated by the JSON library.
    #[error(transparent)]
    Json(#[from] serde_json::Error),

    /// Errors generated by the async sqlite library.
    #[error(transparent)]
    AsyncSqlite(#[from] async_sqlite::Error),

    /// Errors generated by the rusqlite library.
    #[error(transparent)]
    Rusqlite(#[from] async_sqlite::rusqlite::Error),

    /// Error generated by the ZIP library.
    #[error(transparent)]
    Zip(#[from] async_zip::error::ZipError),

    /// Errors generated by the core library.
    #[error(transparent)]
    Core(#[from] sos_core::Error),

    /// Errors generated by the vault library.
    #[error(transparent)]
    Vault(#[from] sos_vault::Error),
}
