[package]
name = "sos-system-messages"
version = "0.17.1"
edition = "2021"
description = "System message notifications for the Save Our Secrets SDK"
homepage = "https://saveoursecrets.com"
license = "MIT OR Apache-2.0"
repository = "https://github.com/saveoursecrets/sdk"

[dependencies]
async-trait.workspace = true
thiserror.workspace = true
serde.workspace = true
time.workspace = true
tokio.workspace = true
urn.workspace = true
serde_with.workspace = true
tracing.workspace = true

[build-dependencies]
rustc_version.workspace = true
