[package]
name = "sos-net"
version = "0.8.0"
edition = "2021"
description = "Networking library for the Save Our Secrets SDK."
homepage = "https://saveoursecrets.com"
license = "MIT OR Apache-2.0"
repository = "https://github.com/saveoursecrets/sdk"

[features]
default = []
full = [
  "archive",
  "client",
  "contacts",
  "device",
  "files",
  "hashcheck",
  "listen",
  "migrate",
  "search",
  "server",
  "security-report",
]
client = [
  "dep:reqwest",
]
listen = ["dep:tokio-tungstenite"]
server = [
  "dep:toml",
  "dep:axum",
  "dep:axum-extra",
  "dep:axum-macros",
  "dep:axum-server",
  "dep:tower",
  "dep:tower-http",
  "dep:async-stream",
  "dep:tokio-stream",
  "device",
]
hashcheck = []
archive = ["sos-sdk/archive"]
files = ["sos-sdk/files"]
contacts = ["sos-sdk/contacts"]
migrate = ["sos-sdk/migrate"]
device = ["sos-sdk/device"]
recovery = ["sos-sdk/recovery"]
search = ["sos-sdk/search"]
security-report = ["sos-sdk/security-report"]
mem-fs = ["sos-sdk/mem-fs"]
test-utils = ["sos-sdk/test-utils"]

[dependencies]
tokio-util.workspace = true
thiserror.workspace = true
tracing.workspace = true
tracing-subscriber.workspace = true
async-trait.workspace = true
async-recursion.workspace = true
http.workspace = true
serde_json.workspace = true
serde.workspace = true
uuid.workspace = true
hex.workspace = true
sha3.workspace = true
web3-signature = { version = "0.4", features = ["single-party"] }
web3-address = { version = "0.6", features = ["ethereum"] }
serde_with = "2"
rand = "0.8"
url = "2"
urlencoding = "2"
futures = "0.3"
pin-project-lite = "0.2"
tempfile = "3.5"
bs58 = "0.4"
secrecy = "0.8"
log = "0.4"
once_cell = "1"
parking_lot = "0.12"
ouroboros = "0.17"

# server
toml = { version = "0.5", optional = true }
axum = { version = "0.7", features = ["ws"], optional = true }
axum-extra = {version = "0.9", features = ["typed-header"], optional = true}
axum-macros = { version = "0.4", optional = true }
axum-server = { version = "0.6", features = ["tls-rustls"], optional = true }
tower = { version = "0.4", optional = true }
tower-http = { version = "0.5", features = ["cors", "trace"], optional = true }
async-stream = { version = "0.3", optional = true }
tokio-stream = { version = "0.1", optional = true }
tokio-tungstenite = { version = "0.21", features = ["rustls-tls-native-roots"] , optional = true}

[dependencies.sos-sdk]
version = "0.8"
features = ["sync"]
path = "../sdk"

[dependencies.binary-stream]
version = "8.0.0"
features = ["async"]
#path = "../../../../binary-stream"

[target.'cfg(not(target_arch="wasm32"))'.dependencies]
file-guard = "0.1"
tokio = { version = "1", features = ["rt", "rt-multi-thread", "time", "sync", "macros"] }

[target.'cfg(target_arch="wasm32")'.dependencies]
tokio = { version = "1", features = ["rt", "time", "sync"] }

[target.'cfg(target_os="macos")'.dependencies]
reqwest = { version = "0.11.22", default-features = true, features = ["json", "rustls-tls", "stream"], optional = true }

# NOTE: Must disable default-features so that openssl
# NOTE: is not compiled when cross-compiling in CI.
#
# NOTE: If we disable `default-features` during
# NOTE: development then attempting to connect to 
# NOTE: the changes feed using the locally issued mkcert
# NOTE: certificate yields an "Unknown Issuer" error.
# NOTE: Which is related to the `security-framework` not 
# NOTE: being compiled on macos when `default-features` is 
# NOTE: disabled.
[target.'cfg(not(target_os="macos"))'.dependencies]
reqwest = { version = "0.11.22", default-features = false, features = ["json", "rustls-tls", "stream"], optional = true }

[dev-dependencies]
anyhow = "1"

[build-dependencies]
rustc_version = "0.4.0"

[package.metadata.docs.rs]
all-features = true
