//! Errors generated by the password library.
use thiserror::Error;

/// Error thrown by the core library.
#[derive(Debug, Error)]
pub enum Error {
    /// Error generated when secret meta data does not exist.
    #[error(
        "too few words for diceware passphrase generation, got {0} but minimum is {1}"
    )]
    DicewareWordsTooFew(usize, u8),
}
