[package]
name = "sos-check"
version = "0.1.0"
edition = "2021"
default-run = "sos-check"
publish = false

[dependencies]
thiserror = "1"
sos-core = { path = "../core", version = "0.1.0" }
clap = { version = "4", features = ["derive", "wrap_help"] }
tracing = "0.1"
tracing-subscriber = { version = "0.3.16", features = ["env-filter"] }
hex = "0.4"
uuid = "1"

[[bin]]
name = "sos-check"
path = "src/main.rs"

[package.metadata.release]
release = false
shared-version = true
