[package]
name = "sos-database"
version = "0.16.0"
edition = "2021"
description = "Database storage layer for the Save Our Secrets SDK"
homepage = "https://saveoursecrets.com"
license = "MIT OR Apache-2.0"
repository = "https://github.com/saveoursecrets/sdk"

[package.metadata.docs.rs]
all-features = true
rustdoc-args = ["--cfg", "docsrs"]

[features]
full = [
  "archive",
  "audit",
  "files",
  "search",
]
archive = ["sos-sdk/archive"]
audit = ["sos-sdk/audit"]
files = ["sos-sdk/files", "dep:tokio-util", "dep:age"]
search = [
  "dep:probly-search",
  "dep:unicode-segmentation",
  "dep:url",
  "dep:vcard4",
]

[dependencies]
sos-core.workspace = true
sos-sdk.workspace = true

thiserror.workspace = true
futures.workspace = true
tracing.workspace = true
serde_json.workspace = true
uuid.workspace = true
indexmap.workspace = true
async-trait.workspace = true
secrecy.workspace = true
sha2.workspace = true
serde.workspace = true
typeshare.workspace = true

tokio-util = { workspace = true, optional = true }
age  = { workspace = true, optional = true }

# search
unicode-segmentation = { workspace = true, optional = true }
probly-search = { workspace = true, optional = true }
url  = { workspace = true, optional = true }
vcard4 = { workspace = true, optional = true }

async-sqlite = "0.3"
refinery = {version = "0.8", git = "https://github.com/rust-db/refinery", features = ["rusqlite"]}
tokio = {version = "1", features = ["sync", "macros"]}

[dev-dependencies]
anyhow.workspace = true
tempfile.workspace = true

