[package]
name = "sos-sdk"
version = "0.16.4"
edition = "2021"
description = "Distributed, encrypted database for private secrets."
homepage = "https://saveoursecrets.com"
license = "MIT OR Apache-2.0"
categories = ["cryptography::cryptocurrencies", "authentication"]
repository = "https://github.com/saveoursecrets/sdk"

[lib]
crate-type = ["cdylib", "rlib"]

[package.metadata.docs.rs]
all-features = true
rustdoc-args = ["--cfg", "docsrs"]

[features]
default = ["audit", "logs"]
full = [
  "archive",
  "audit",
  "contacts",
  "files",
  "logs",
  "search",
]
archive = []
audit = []
contacts = []
files = []
interactive-keychain-tests = []
logs = ["rev_buf_reader", "tracing-appender", "tracing-subscriber"]
mem-fs = ["sos-vfs/mem-fs"]
recovery = ["dep:vsss-rs"]
search = ["dep:probly-search"]

[dependencies]
sos-core.workspace = true
sos-vfs.workspace = true

binary-stream.workspace = true
secrecy.workspace = true
tokio-util.workspace = true
tracing.workspace = true
thiserror.workspace = true
async-trait.workspace = true
serde.workspace = true
serde_json.workspace = true
uuid.workspace = true
hex.workspace = true
k256.workspace = true
sha1.workspace = true
sha2.workspace = true
sha3.workspace = true
serde_with.workspace = true
once_cell.workspace = true
rand.workspace = true
url.workspace = true
time.workspace = true
time-tz.workspace = true
futures.workspace = true
parking_lot.workspace = true
bs58.workspace = true
indexmap.workspace = true
bitflags.workspace = true
tempfile.workspace = true
typeshare.workspace = true
totp-rs.workspace = true

subtle = { version = "2.5" }
ethereum-types = "0.15"

aes-gcm = { version = "0.10.1", features = ["std"] }
chacha20poly1305 = { version = "0.10.1", features = ["std"] }
filetime = "0.2"
argon2 = { version = "0.5", features = ["std"]}
balloon-hash = { version = "0.4", features = ["std"]}
pem = { version = "3", features = ["serde"] }
zxcvbn = { version = "3.0.1", features = ["ser"] }
vcard4.workspace = true
async-once-cell = "0.5"
age.workspace = true
ed25519-dalek = { version = "2.1.1", features = ["rand_core"] }
urn = { version = "0.7", features = ["serde"] }
walkdir = "2"
unicode-segmentation = "1.10"
mime_guess = { version = "2" }
futures-util.workspace = true
async-stream = "0.3"
whoami = { version = "1.5" }
vsss-rs = {version = "3", optional = true }
tracing-appender = { version = "0.2", optional = true }
tracing-subscriber = { version = "0.3.16", features = ["env-filter", "json"], optional = true }
rev_buf_reader = { version = "0.3", optional = true }

[dependencies.probly-search]
version = "2.0.1"
optional = true

[target.'cfg(not(target_arch = "wasm32"))'.dependencies]
tokio = { version = "1", default-features = false, features = ["rt", "fs", "io-util", "sync"] }
etcetera = "0.8"

[target.'cfg(target_arch = "wasm32")'.dependencies]
getrandom = {version = "0.2", features = ["js"]}
uuid = { version = "1", features = ["serde", "v4", "js"] }
tokio = { version = "1", default-features = false, features = ["rt", "sync", "macros", "io-util"] }

[dependencies.chbs]
version = "0.1.1"

[dev-dependencies]
anyhow.workspace = true
tokio = { version = "1", features = ["full"] }
sos-test-utils.workspace = true

[build-dependencies]
rustc_version = "0.4.1"
