[package]
name = "sos-sdk"
version = "0.16.5"
edition = "2021"
description = "Distributed, encrypted database for private secrets."
homepage = "https://saveoursecrets.com"
license = "MIT OR Apache-2.0"
categories = ["cryptography::cryptocurrencies", "authentication"]
repository = "https://github.com/saveoursecrets/sdk"

[lib]
crate-type = ["cdylib", "rlib"]

[package.metadata.docs.rs]
all-features = true
rustdoc-args = ["--cfg", "docsrs"]

[features]
full = [
  "contacts",
  "files",
]
contacts = []
files = ["sos-core/files"]

[dependencies]
sos-core.workspace = true
sos-login.workspace = true
sos-password.workspace = true
sos-signer.workspace = true
sos-vault.workspace = true
sos-vfs.workspace = true

[build-dependencies]
rustc_version.workspace = true
