[package]
name = "sos-sdk"
version = "0.16.4"
edition = "2021"
description = "Distributed, encrypted database for private secrets."
homepage = "https://saveoursecrets.com"
license = "MIT OR Apache-2.0"
categories = ["cryptography::cryptocurrencies", "authentication"]
repository = "https://github.com/saveoursecrets/sdk"

[lib]
crate-type = ["cdylib", "rlib"]

[package.metadata.docs.rs]
all-features = true
rustdoc-args = ["--cfg", "docsrs"]

[features]
default = ["audit", "logs"]
full = [
  "archive",
  "audit",
  "contacts",
  "files",
  "logs",
  "search",
]
archive = []
audit = []
contacts = []
files = []
logs = ["rev_buf_reader", "tracing-appender", "tracing-subscriber"]
mem-fs = ["sos-vfs/mem-fs"]
recovery = ["dep:vsss-rs"]
search = ["dep:probly-search", "dep:unicode-segmentation"]

[dependencies]
sos-core.workspace = true
sos-password.workspace = true
sos-vfs.workspace = true

binary-stream.workspace = true
secrecy.workspace = true
tokio-util.workspace = true
tracing.workspace = true
thiserror.workspace = true
async-trait.workspace = true
serde.workspace = true
serde_json.workspace = true
uuid.workspace = true
hex.workspace = true
sha1.workspace = true
sha2.workspace = true
sha3.workspace = true
serde_with.workspace = true
once_cell.workspace = true
rand.workspace = true
url.workspace = true
time.workspace = true
time-tz.workspace = true
futures.workspace = true
parking_lot.workspace = true
bs58.workspace = true
indexmap.workspace = true
bitflags.workspace = true
tempfile.workspace = true
typeshare.workspace = true
totp-rs.workspace = true
vcard4.workspace = true
urn.workspace = true
futures-util.workspace = true
async-stream.workspace = true
pem.workspace = true
tokio.workspace = true

# crypto
age.workspace = true
argon2.workspace = true
aes-gcm.workspace = true
chacha20poly1305.workspace = true
balloon-hash.workspace = true

# signing
ethereum-types = "0.15"
subtle = "2.5"
k256.workspace = true
ed25519-dalek = { version = "2.1.1", features = ["rand_core"] }

# search
unicode-segmentation = { version = "1.10", optional = true }
probly-search = { version = "2.0.1", optional = true }

async-once-cell = "0.5"
whoami = { version = "1.5" }
vsss-rs = {version = "3", optional = true }

# logs
tracing-appender = { version = "0.2", optional = true }
tracing-subscriber = { version = "0.3.16", features = ["env-filter", "json"], optional = true }
rev_buf_reader = { version = "0.3", optional = true }

[target.'cfg(not(target_arch = "wasm32"))'.dependencies]
etcetera = "0.8"

[target.'cfg(target_arch = "wasm32")'.dependencies]
getrandom = {version = "0.2", features = ["js"]}
uuid = { version = "1", features = ["serde", "v4", "js"] }

[dev-dependencies]
anyhow.workspace = true
sos-test-utils.workspace = true

[build-dependencies]
rustc_version.workspace = true
