[package]
name = "sos-sdk"
version = "0.17.0"
edition = "2021"
description = "Distributed, encrypted database for private secrets."
homepage = "https://saveoursecrets.com"
license = "MIT OR Apache-2.0"
categories = ["cryptography::cryptocurrencies", "authentication"]
repository = "https://github.com/saveoursecrets/sdk"

[package.metadata.docs.rs]
all-features = true
rustdoc-args = ["--cfg", "docsrs"]

[features]
full = ["files"]
files = ["sos-core/files", "sos-login/files"]

[dependencies]
sos-core.workspace = true
sos-login.workspace = true
sos-password.workspace = true
sos-signer.workspace = true
sos-vault.workspace = true
sos-vfs.workspace = true

[build-dependencies]
rustc_version.workspace = true
