[package]
name = "sos-sync"
version = "0.16.0"
edition = "2021"
description = "Core sync types and traits for the Save Our Secrets SDK"
homepage = "https://saveoursecrets.com"
license = "MIT OR Apache-2.0"
repository = "https://github.com/saveoursecrets/sdk"

[package.metadata.docs.rs]
all-features = true
rustdoc-args = ["--cfg", "docsrs"]

[features]
full = ["files"]
files = ["sos-filesystem/files"]

[dependencies]
sos-core.workspace = true
sos-filesystem.workspace = true
sos-vault.workspace = true

thiserror.workspace = true
async-trait.workspace = true
indexmap.workspace = true
tokio.workspace = true
tracing.workspace = true

[build-dependencies]
rustc_version.workspace = true
