[package]
name = "sos-remote-sync"
version = "0.17.0"
edition = "2021"
description = "Sync protocol implementation for the Save Our Secrets SDK."
homepage = "https://saveoursecrets.com"
license = "MIT OR Apache-2.0"
repository = "https://github.com/saveoursecrets/sdk"

[package.metadata.docs.rs]
all-features = true
rustdoc-args = ["--cfg", "docsrs"]

[features]
full = ["files"]
files = [
  "sos-account/files",
  "sos-backend/files",
  "sos-protocol/files",
  "sos-sync/files",
]

[dependencies]
sos-account.workspace = true
sos-backend.workspace = true
sos-core.workspace = true
sos-protocol.workspace = true
sos-sync.workspace = true
sos-vfs.workspace = true

async-trait.workspace = true
thiserror.workspace = true
indexmap.workspace = true
tokio.workspace = true
tracing.workspace = true

[build-dependencies]
rustc_version.workspace = true
