[package]
name = "sos"
version = "0.16.1"
edition = "2021"
description = "Distributed, encrypted database for private secrets."
homepage = "https://saveoursecrets.com"
license = "MIT OR Apache-2.0"
authors = ["saveoursecrets-developers <dev@saveoursecrets.com>"]
categories = [
  "command-line-utilities",
  "cryptography::cryptocurrencies",
  "authentication"
]

[features]
default = []
enable-cli-tests = []

[dependencies]
sos-account.workspace = true
sos-core.workspace = true
sos-cli-helpers.workspace = true
sos-client-storage.workspace = true
sos-database = { workspace = true, features = ["full"] }
sos-filesystem.workspace = true
sos-integrity.workspace = true
sos-logs.workspace = true
sos-password.workspace = true
sos-protocol = { workspace = true, features = ["full"] }
sos-net = { workspace = true, features = ["full"] }
sos-migrate.workspace = true
sos-sdk = { workspace = true, features = ["full"] }
sos-sync.workspace = true
sos-vault.workspace = true

csv-async.workspace = true
binary-stream.workspace = true
tracing.workspace = true
tracing-subscriber.workspace = true
serde_json.workspace = true
thiserror.workspace = true
async-recursion.workspace = true
futures.workspace = true
parking_lot.workspace = true
once_cell.workspace = true
toml.workspace = true
serde.workspace = true
enum-iterator.workspace = true
clap.workspace = true
arboard.workspace = true
sha2.workspace = true
zxcvbn.workspace = true
tokio-rustls.workspace = true
rustls.workspace = true
tempfile.workspace = true

human_bytes = "0.4"
shell-words = "1"
terminal-banner = { version = "0.4.1", features = ["color"] }
unicode-width = "0.2"
kdam = { version = "0.6", features = ["rich", "spinner"] }
crossterm = "0.28"
ctrlc = "3"
tokio = { version = "1", features = ["rt", "rt-multi-thread", "time", "sync"] }
rustyline = "14"
rustyline-derive = "0.11"

