use thiserror::Error;

#[derive(Debug, Error)]
pub enum Error {
    /// Server storage errors.
    #[cfg(feature = "server")]
    #[error(transparent)]
    Server(#[from] crate::server::Error),

    /// Errors generated by the SDK library.
    #[error(transparent)]
    Sdk(#[from] sos_sdk::Error),

    /// Errors generated by the protocol library.
    #[error(transparent)]
    Protocol(#[from] sos_protocol::Error),

    /// Errors generated by the IO module.
    #[error(transparent)]
    Io(#[from] std::io::Error),
}
