//! Error type for the pairing module.
use crate::sync::SyncError;
use thiserror::Error;

/// Errors generated by the pairing library.
#[derive(Debug, Error)]
pub enum Error {
    /// Error generated trying to parse a pairing URL.
    #[error("invalid pairing url")]
    InvalidShareUrl,

    /// Error generated if a packet has a to public key that does not
    /// match the recipient key pair.
    #[error("packet is not for me (wrong public key)")]
    NotForMe,

    /// Error generated failing to sync devices patch.
    #[error("failed to sync devices: {0}")]
    DevicePatchSync(SyncError<crate::client::Error>),

    /// Error generated trying to access device enrollment
    /// before pairing protocol completion.
    #[error("enrollment is not available")]
    NoEnrollment,

    /// Error generated trying to finish device enrollment
    /// before fetching the account data.
    #[error("account must be fetched before authenticating a new device")]
    AccountNotFetched,

    /// Error generated attempting to enroll a new device and
    /// the account already exists on the device.
    #[error("cannot enroll, account '{0}' already exists on this device")]
    EnrollAccountExists(String),

    /// Error generated when failing to sync after completing
    /// device enrollment.
    #[error("could not sync after device enrollment authentication: '{0}'")]
    EnrollSync(SyncError<crate::client::Error>),

    /// Error generated when the protocol is in the wrong state
    /// or a packet payload is not of the expected type.
    #[error("pairing protocol bad state or invalid packet payload")]
    BadState,

    /// Error generated by the client library.
    #[error(transparent)]
    Client(#[from] crate::client::Error),

    /// Error generated by the SDK library.
    #[error(transparent)]
    Sdk(#[from] crate::sdk::Error),

    /// Error generated by the io module.
    #[error(transparent)]
    Io(#[from] std::io::Error),

    /// Error generated by the JSON library.
    #[error(transparent)]
    Json(#[from] serde_json::Error),

    /// Error generated when parsing from hex.
    #[error(transparent)]
    Hex(#[from] hex::FromHexError),

    /// Error generated attempting to convert from a slice.
    #[error(transparent)]
    TryFromSlice(#[from] std::array::TryFromSliceError),

    /// Error generated attempting to parse a URL.
    #[error(transparent)]
    UrlParse(#[from] url::ParseError),

    /// Error generated by the snow noise protocol library.
    #[error(transparent)]
    Snow(#[from] snow::Error),

    /// Error generated by the websocket client.
    #[error(transparent)]
    WebSocket(#[from] tokio_tungstenite::tungstenite::Error),

    /// Error generated by the protocol module.
    #[error(transparent)]
    Protocol(#[from] crate::protocol::Error),

    /// Error generated by the protobuf library when encoding.
    #[error(transparent)]
    ProtoBufEncode(#[from] prost::EncodeError),

    /// Error generated by the protobuf library when decoding.
    #[error(transparent)]
    ProtoBufDecode(#[from] prost::DecodeError),
}
