[package]
name = "sos-wasm"
version = "0.1.0"
edition = "2021"
description = "Bindings for Webassembly"

[lib]
crate-type = ["cdylib", "rlib"]

[dependencies]
sos-core = { path = "../core" }
wasm-bindgen = { version = "0.2.80", features = ["serde-serialize"] }
web3-keystore = "0.4"
console_error_panic_hook = "0.1.7"
serde = {version = "1", features = ["derive"]}
url = { version = "2.2", features = ["serde"] }
mime_guess = "2"
rand = "0.8"
getrandom = { version = "0.2", features = ["js"] }
