[package]
name = "sos-node"
version = "0.1.0"
edition = "2021"
description = "Distributed, encrypted database for private secrets."
homepage = "https://saveoursecrets.com"
license = "GPL-3.0"

[dependencies]
sos-core = { path = "../core", version = "0.1.0" }

thiserror = "1"
tracing = "0.1"
tracing-subscriber = { version = "0.3", features = ["env-filter"] }
async-trait = "0.1"
async-recursion = "1"
k256 = { version = "0.10", features = ["ecdsa", "sha256", "keccak256"] }
web3-signature = { version = "0.2", features = ["single-party"] }
serde = "1"
serde_json = "1"
rand = "0.8"
tokio = { version = "1", features = ["rt", "rt-multi-thread"] }
url = "2"
futures = "0.3"
pin-project-lite = "0.2"
uuid = { version = "1", features = ["serde", "v4"] }
base64 = "0.13"
hex = "0.4"
tempfile = "3"
dirs = "4"
http = "0.2"

# client
reqwest-eventsource = { version = "0.4", path = "../../../../forks/reqwest-eventsource", optional = true }
web3-keystore = { version = "0.4", optional = true }

# server
toml = { version = "0.5", optional = true }
axum = { version = "0.5", features = ["headers"], optional = true }
axum-macros = { version = "0.2", optional = true }
axum-server = { version = "0.4", features = ["tls-rustls"], optional = true }
hyper = { version = "0.14", features = ["full"], optional = true }
tower = { version = "0.4", optional = true }
tower-http = { version = "0.2", features = ["full"], optional = true }
once_cell = { version = "1.10", optional = true }
sha3 = { version = "0.10", optional = true }
rust-embed = { version = "6", optional = true }
mime_guess = { version = "2", optional = true }
async-stream = { version = "0.3", optional = true }

[target.'cfg(any(not(target_arch="aarch64"),not(target_os="linux")))'.dependencies]
reqwest = { version = "0.11", path = "../../../../forks/reqwest", default-features = true, features = ["json", "rustls-tls"], optional = true }

# NOTE: Must disable default-features so that openssl
# NOTE: is not compiled when cross-compiling in CI.
#
# NOTE: If we disable `default-features` during
# NOTE: development then attempting to connect to 
# NOTE: the changes feed using the locally issued mkcert
# NOTE: certificate yields an "Unknown Issuer" error.
# NOTE: Which is related to the `security-framework` not 
# NOTE: being compiled on macos when `default-features` is 
# NOTE: disabled.
[target.'cfg(all(target_arch="aarch64",target_os="linux"))'.dependencies]
reqwest = { version = "0.11", path = "../../../../forks/reqwest", default-features = false, features = ["json", "rustls-tls"], optional = true }

[features]
default = ["node"]
client = [
  "reqwest",
  "reqwest-eventsource",
  "web3-keystore",
]
node = ["client", "server"]
server = [
  "toml",
  "axum",
  "axum-macros",
  "axum-server",
  "hyper",
  "tower",
  "tower-http",
  "once_cell",
  "sha3",
  "rust-embed",
  "mime_guess",
  "async-stream",
]
gui = []

[package.metadata.release]
tag = false
shared-version = true
