[package]
name = "sos-node"
version = "0.1.0"
edition = "2021"
description = "Distributed, encrypted database for private secrets."
homepage = "https://saveoursecrets.com"
license = "GPL-3.0"

[dependencies]
sos-core = { path = "../sdk", version = "0.1.0" }

thiserror = "1"
tracing = "0.1"
tracing-subscriber = { version = "0.3", features = ["env-filter"] }
async-trait = "0.1"
async-recursion = "1"
web3-signature = { version = "0.4", features = ["single-party"] }
web3-address = { version = "0.6", features = ["ethereum"] }
serde = "1"
serde_json = "1"
rand = "0.8"
url = "2"
futures = "0.3"
pin-project-lite = "0.2"
uuid = { version = "1", features = ["serde", "v4"] }
hex = "0.4"
tempfile = "3"
dirs = "4"
http = "0.2"
bs58 = "0.4"
secrecy = "0.8"
log = "0.4"
crypto-bigint = "0.4.8"
sha3 = "0.10"
once_cell = "1"
parking_lot = "0.12"
ouroboros = "0.15"

# server
toml = { version = "0.5", optional = true }
axum = { version = "0.5.17", features = ["headers", "ws"], optional = true }
axum-macros = { version = "0.2", optional = true }
axum-server = { version = "0.4", features = ["tls-rustls"], optional = true }
hyper = { version = "0.14", features = ["full"], optional = true }
tower = { version = "0.4", optional = true }
tower-http = { version = "0.3", features = ["full"], optional = true }
mime_guess = { version = "2", optional = true }
async-stream = { version = "0.3", optional = true }
tokio-stream = { version = "0.1", optional = true }

# device
whoami = { version = "1.4", optional = true }
if-addrs = { version = "0.10.1", optional = true }

# peer
void = { version = "1", optional = true }
either = { version = "1.8", optional = true }

[dependencies.libp2p]
version = "0.51"
git = "https://github.com/tmpfs/rust-libp2p"
branch = "snow-hacks"
#path = "../../../../forks/libp2p/libp2p"
optional = true
features = [
  "tokio", 
  "gossipsub",
  "noise",
  "macros",
  "tcp",
  "yamux",
  "kad",
  "request-response",
  "rendezvous",
  "identify",
]

[dependencies.libp2p-quic]
version = "0.7.0-alpha.3"
git = "https://github.com/tmpfs/rust-libp2p"
branch = "snow-hacks"
#path = "../../../../forks/libp2p/transports/quic"
features = ["tokio"]
optional = true

[target.'cfg(not(target_arch="wasm32"))'.dependencies]
file-guard = "0.1"
tokio = { version = "1", features = ["rt", "rt-multi-thread", "time", "sync"] }
#parity-tokio-ipc = { version = "0.9", optional = true }
#binary-stream = { version = "3.4", features = ["32bit"], optional = true }
tokio-tungstenite = { version = "0.17.2", features = ["rustls-tls-native-roots"] }

[target.'cfg(target_arch="wasm32")'.dependencies]
tokio = { version = "1", features = ["rt", "time", "sync"] }

[target.'cfg(any(target_family="unix",target_family="windows"))'.dependencies]
reqwest = { version = "0.11", default-features = true, features = ["json", "rustls-tls"], optional = true }

# NOTE: Must disable default-features so that openssl
# NOTE: is not compiled when cross-compiling in CI.
#
# NOTE: If we disable `default-features` during
# NOTE: development then attempting to connect to 
# NOTE: the changes feed using the locally issued mkcert
# NOTE: certificate yields an "Unknown Issuer" error.
# NOTE: Which is related to the `security-framework` not 
# NOTE: being compiled on macos when `default-features` is 
# NOTE: disabled.
[target.'cfg(any(all(target_arch="aarch64",target_os="linux"),any(target_os = "android", target_os="ios"), target_family = "wasm"))'.dependencies]
reqwest = { version = "0.11", default-features = false, features = ["json", "rustls-tls"], optional = true }

[dev-dependencies]
anyhow = "1"

[features]
default = ["node"]
client = [
  "reqwest",
]
node = ["client", "server"]
peer = ["libp2p", "libp2p-quic", "either", "void"]
server = [
  "toml",
  "axum",
  "axum-macros",
  "axum-server",
  "hyper",
  "tower",
  "tower-http",
  "mime_guess",
  "async-stream",
  "tokio-stream",
]
device = [
  "if-addrs",
  "whoami",
]

[build-dependencies]
rustc_version = "0.4.0"

[package.metadata.release]
tag = false
shared-version = true

[package.metadata.docs.rs]
all-features = true
