[package]
name = "sos-node"
version = "0.1.0"
edition = "2021"

[dependencies]
thiserror = "1"
async-trait = "0.1"
async-recursion = "1"
sos-core = { path = "../core", version = "0.1.0" }
web3-keystore = "0.4"
web3-signature = { version = "0.2.3", features = ["single-party"] }
serde_json = "1"
rand = "0.8"
tracing = "0.1"
tracing-subscriber = { version = "0.3", features = ["env-filter"] }
tokio = { version = "1", features = ["full"] }
url = "2"
reqwest-eventsource = "0.4"
futures = "0.3"
uuid = { version = "1", features = ["serde", "v4"] }
base64 = "0.13"
hex = "0.4"
tempfile = "3"
dirs = "4"

[target.'cfg(any(not(target_arch="aarch64"),not(target_os="linux")))'.dependencies]
reqwest = { version = "0.11", default-features = true, features = ["json", "rustls-tls"] }

# NOTE: Must disable default-features so that openssl
# NOTE: is not compiled when cross-compiling in CI.
#
# NOTE: If we disable `default-features` during
# NOTE: development then attempting to connect to 
# NOTE: the changes feed using the locally issued mkcert
# NOTE: certificate yields an "Unknown Issuer" error.
# NOTE: Which is related to the `security-framework` not 
# NOTE: being compiled on macos when `default-features` is 
# NOTE: disabled.
[target.'cfg(all(target_arch="aarch64",target_os="linux"))'.dependencies]
reqwest = { version = "0.11", default-features = false, features = ["json", "rustls-tls"] }

[package.metadata.release]
tag = false
shared-version = true

