[package]
name = "sos-sdk"
version = "0.5.0"
edition = "2021"
description = "Distributed, encrypted database for private secrets."
homepage = "https://saveoursecrets.com"
license = "GPL-3.0"
categories = ["cryptography::cryptocurrencies", "authentication"]

[lib]
crate-type = ["cdylib", "rlib"]

[features]
mem-fs = []
test-utils = ["dep:anyhow"]

[dependencies]
async-trait = "0.1"
async-recursion = "1"
aes-gcm = { version = "0.10.1", features = ["std"] }
chacha20poly1305 = { version = "0.10.1", features = ["std"] }
tracing = "0.1"
filetime = "0.2"
rand = "0.8"
thiserror = "1"
web3-signature = { version = "0.4", features = ["single-party"] }
web3-address = { version = "0.6", features = ["ethereum"] }
serde = { version = "1", features = ["derive"] }
hex = { version = "0.4", features = ["serde"] }
serde_json = "1"
k256 = { version = "0.13.1", features = ["ecdsa", "ecdh"] }
subtle = "2"
zeroize = { version = "1", features = ["zeroize_derive"] }
argon2 = { version = "0.5", features = ["std"]}
# matches the version in k256
sha3 = "0.10.6"
sha2 = "0.10.6"
dirs = "4"
uuid = { version = "1", features = ["serde", "v4"] }
url = { version = "2", features = ["serde"] }
bitflags = "1"
pem = { version = "2", features = ["serde"] }
secrecy = { version = "0.8", features = ["serde"] }
crypto-bigint = "0.5"
tempfile = "3"
log = "0.4"
http = "0.2"
zxcvbn = "2"
totp-sos = { version = "3", features = ["serde"] }
vcard4 = { version = "0.4.4", features = ["serde"] }
parking_lot = "0.12"
once_cell = "1"
age = "0.9"
ed25519-dalek = { version = "2.0.0-rc.2", features = ["rand_core"] }
bs58 = "0.4"
urn = { version = "0.7", features = ["serde"] }
walkdir = "2"
binary-stream = { version = "5.0.0", features = ["32bit", "tokio"], path = "../../../../binary-stream" }
zip = { version = "0.6", default-features = false, features = ["deflate"] }
time = { version = "0.3.19", features = ["serde-human-readable", "local-offset", "wasm-bindgen"] }
unicode-segmentation = "1.10"
mime_guess = { version = "2" }
anyhow = {version = "1", optional = true }
futures = "0.3"

[dependencies.probly-search]
version = "2.0.0-alpha-2"
#path = "../../../../forks/probly-search"
git = "https://github.com/tmpfs/probly-search/"
branch = "multi-field"

[target.'cfg(not(target_arch = "wasm32"))'.dependencies]
tokio = { version = "1", default-features = false, features = ["fs", "io-util", "sync"] }

[target.'cfg(target_arch = "wasm32")'.dependencies]
getrandom = {version = "0.2", features = ["js"]}
uuid = { version = "1", features = ["serde", "v4", "js"] }
tokio = { version = "1", default-features = false, features = ["rt", "sync", "macros"] }

[dependencies.rs_merkle]
version = "1.2"
git = "https://github.com/tmpfs/rs-merkle"
branch = "sha2-update"
#path = "../../../../forks/rs-merkle"

[dependencies.chbs]
version = "0.1.1"
#git = "https://gitlab.com/timvisee/chbs.git"
#rev = "1bb19733ac66cebf58b726d14770a616faba85dd"
#branch = "wasm32"

[build-dependencies]
rustc_version = "0.4.0"

[dev-dependencies]
anyhow = "1"
tokio = { version = "1", features = ["full"] }
serial_test = "2"

[package.metadata.release]
tag = false
shared-version = true

[package.metadata.docs.rs]
all-features = true
