[package]
name = "sos-sdk"
version = "0.5.4"
edition = "2021"
description = "Distributed, encrypted database for private secrets."
homepage = "https://saveoursecrets.com"
license = "GPL-3.0"
categories = ["cryptography::cryptocurrencies", "authentication"]
repository = "https://github.com/saveoursecrets/sdk"

[lib]
crate-type = ["cdylib", "rlib"]

[features]
mem-fs = []
test-utils = ["dep:anyhow"]
keyring = ["dep:keyring"]

[dependencies]
async-trait = "0.1"
async-recursion = "1"
aes-gcm = { version = "0.10.1", features = ["std"] }
chacha20poly1305 = { version = "0.10.1", features = ["std"] }
tracing = "0.1"
filetime = "0.2"
rand = "0.8"
thiserror = "1"
web3-signature = { version = "0.4", features = ["single-party"] }
web3-address = { version = "0.6", features = ["ethereum"] }
serde = { version = "1", features = ["derive"] }
hex = { version = "0.4", features = ["serde"] }
serde_json = "1"
k256 = { version = "0.13.1", features = ["ecdsa"] }
subtle = "2"
zeroize = { version = "1", features = ["zeroize_derive"] }
argon2 = { version = "0.5", features = ["std"]}
balloon-hash = { version = "0.4", features = ["std"]}
# matches the version in k256
sha3 = "0.10.6"
sha2 = "0.10.6"
app_dirs2 = "2"
uuid = { version = "1", features = ["serde", "v4"] }
url = { version = "2", features = ["serde"] }
bitflags = "1"
pem = { version = "2", features = ["serde"] }
secrecy = { version = "0.8", features = ["serde"] }
tempfile = "3.5"
log = "0.4"
http = "0.2"
zxcvbn = "2"
totp-sos = { version = "3", features = ["serde"] }
vcard4 = { version = "0.4.4", features = ["serde"] }
parking_lot = "0.12"
once_cell = "1"
age = { version = "0.9", features = ["async"] }
ed25519-dalek = { version = "2.0.0-pre.0", features = ["rand_core"] }
bs58 = "0.4"
urn = { version = "0.7", features = ["serde"] }
walkdir = "2"
time = { version = "0.3.19", features = ["serde-human-readable", "local-offset", "wasm-bindgen"] }
unicode-segmentation = "1.10"
mime_guess = { version = "2" }
anyhow = {version = "1", optional = true }
futures = "0.3"
async_zip = { version = "0.0.15", default-features = false, features = ["deflate", "tokio"] }
sanitize-filename = "0.4"
tokio-util = { version = "0.7", default-features = false, features = ["compat"] }
futures-util = "0.3"
mpc-protocol = "0.4.1"
keyring = {version = "2", optional = true }

[dependencies.binary-stream]
version = "8.0.0"
features = ["async"]
#path = "../../../../binary-stream"

[dependencies.probly-search]
version = "2.0.0-alpha-2"
#path = "../../../../forks/probly-search"
#git = "https://github.com/tmpfs/probly-search/"
#branch = "multi-field"

[target.'cfg(not(target_arch = "wasm32"))'.dependencies]
tokio = { version = "1", default-features = false, features = ["rt", "fs", "io-util", "sync"] }

[target.'cfg(target_arch = "wasm32")'.dependencies]
getrandom = {version = "0.2", features = ["js"]}
uuid = { version = "1", features = ["serde", "v4", "js"] }
tokio = { version = "1", default-features = false, features = ["rt", "sync", "macros", "io-util"] }

[dependencies.rs_merkle]
version = "1.2"
#git = "https://github.com/tmpfs/rs-merkle"
#branch = "sha2-update"
#path = "../../../../forks/rs-merkle"

[dependencies.chbs]
version = "0.1.1"

[build-dependencies]
rustc_version = "0.4.0"

[dev-dependencies]
anyhow = "1"
tokio = { version = "1", features = ["full"] }
serial_test = "2"

[package.metadata.docs.rs]
all-features = true
