[package]
name = "sos-audit"
version = "0.1.0"
edition = "2021"
default-run = "sos-audit"
publish = false

[dependencies]
thiserror = "1"
clap = { version = "4", features = ["derive", "wrap_help"] }
sos-core = { path = "../core", version = "0.1.0" }
serde_json = "1"
tracing = "0.1"
tracing-subscriber = { version = "0.3.16", features = ["env-filter"] }
web3-address = { version = "0.4.1", features = ["ethereum"] }

[[bin]]
name = "sos-audit"
path = "src/main.rs"

[package.metadata.release]
release = false
shared-version = true
