[package]
name = "sos-web"
version = "0.16.5"
edition = "2021"
description = "Thin client for webassembly bindings to the Save Our Secrets SDK."
homepage = "https://saveoursecrets.com"
license = "MIT OR Apache-2.0"
repository = "https://github.com/saveoursecrets/sdk"

[package.metadata.docs.rs]
all-features = true
rustdoc-args = ["--cfg", "docsrs"]

[features]
full = [
  "archive",
  "clipboard",
  "contacts",
  "files",
  "migrate",
  "search",
]
archive = []
clipboard = []
contacts = ["sos-account/contacts", "sos-protocol/contacts"]
files = []
migrate = ["sos-account/migrate", "sos-migrate"]
search = ["sos-database/search", "sos-protocol/search"]

[dependencies]
sos-core.workspace = true
sos-account.workspace = true
sos-database = { workspace = true, features = ["client"] }
sos-sync.workspace = true
sos-client-storage.workspace = true
sos-sdk.workspace = true
sos-protocol = { workspace = true, features = ["network-client"] }
sos-migrate = { workspace = true, optional = true }

thiserror.workspace = true
tracing.workspace = true
indexmap.workspace = true
async-trait.workspace = true
tokio.workspace = true

[build-dependencies]
rustc_version = "0.4.1"

