[package]
name = "sos3_cli"
version = "0.1.0"
edition = "2021"
default-run = "sos3"

[dependencies]
anyhow = "1"
clap = { version = "3", features = ["derive"] }
sos_core = { path = "../core" }
serde_json = "1"
log = "0.4"
pretty_env_logger = "0.4"

[dependencies.rpassword]
version = "5"
#path = "../rpassword"
