[package]
name = "sos-cli"
version = "0.1.0"
edition = "2021"
default-run = "sos3"

[dependencies]
anyhow = "1"
clap = { version = "3", features = ["derive", "wrap_help"] }
sos-core = { path = "../core" }
sos-readline = { path = "../readline" }
serde_json = "1"
log = "0.4"
pretty_env_logger = "0.4"
uuid = { version = "1", features = ["serde", "v4"] }
atty = "0.2"
#rustyline = "9"
#rustyline-derive = "0.6"
#unicode-width = "0.1"
mime_guess = "2"
url = "2"
human_bytes = "0.3"

