use thiserror::Error;

/// Errors generated by the platform authenticator library.
#[derive(Debug, Error)]
pub enum Error {
    /// Error generated when a keyring entry could not be found.
    #[error("keyring entry not found")]
    NoKeyringEntry,

    /// Error generated converting to UTF-8.
    #[cfg(all(not(target_os = "android"), not(target_os = "macos")))]
    #[error(transparent)]
    Keyring(#[from] keyring::Error),

    /// Error generated converting to UTF-8.
    #[error(transparent)]
    Utf8(#[from] std::str::Utf8Error),

    /// Error generated by the security framework.
    #[cfg(target_os = "macos")]
    #[error(transparent)]
    SecurityFramework(#[from] security_framework::base::Error),
}

impl Error {
    /// Determine if this error is a no keyring entry error.
    pub fn is_no_keyring_entry(&self) -> bool {
        matches!(self, Error::NoKeyringEntry)
    }
}
