[package]
name = "sos-client"
version = "0.1.0"
edition = "2021"
default-run = "sos-client"
publish = false

[dependencies]
thiserror = "1"
sos-core = { path = "../core", version = "0.1.0" }
sos-node = { path = "../node", version = "0.1.0", default-features = false, features = ["client", "agent-client"] }
sos-readline = { path = "../readline", version = "0.1.0" }
clap = { version = "3.2.20", features = ["derive", "wrap_help"] }
tokio = { version = "1", features = ["full"] }
url = "2"
futures = "0.3"
serde_json = "1"
uuid = { version = "1", features = ["serde", "v4"] }
hex = "0.4"
tracing = "0.1"
tracing-subscriber = { version = "0.3.16", features = ["env-filter"] }
mime_guess = "2"
human_bytes = "0.3"
tempfile = "3"
sha3 = "0.10"
shell-words = "1"
terminal-banner = "0.1"
zeroize = "1.4" 
secrecy = "0.8"
web3-address = { version = "0.4", features = ["ethereum"] }

vcard4 = { version = "0.1.4", features = ["serde"] }

[[bin]]
name = "sos-client"
path = "src/main.rs"

[package.metadata.release]
release = false
shared-version = true
