[package]
name = "sos-client"
version = "0.1.0"
edition = "2021"

[dependencies]
thiserror = "1"
sos-core = { path = "../core" }
sos-readline = { path = "../readline" }
clap = { version = "3", features = ["derive"] }
tokio = { version = "1", features = ["full"] }
url = "2"
reqwest = "0.11"
k256 = { version = "0.10", features = ["ecdsa", "sha256", "keccak256"] }
web3-keystore = "0.4"
serde_json = "1"
once_cell = "1.12"
