[package]
name = "sos-server"
version = "0.16.1"
edition = "2021"
description = "Server for the Save Our Secrets sync protocol."
homepage = "https://saveoursecrets.com"
license = "AGPL-3.0"
repository = "https://github.com/saveoursecrets/sdk"

[package.metadata.docs.rs]
all-features = true
rustdoc-args = ["--cfg", "docsrs"]

[features]
default = ["listen", "audit", "pairing", "acme"]
prometheus = ["axum-prometheus"]
acme = ["dep:tokio-rustls-acme"]
listen = ["sos-protocol/listen"]
pairing = ["sos-protocol/pairing"]
audit = ["sos-audit"]

[dependencies]
sos-audit = { workspace = true, optional = true }
sos-core.workspace = true
sos-sdk.workspace = true
sos-database.workspace = true
sos-filesystem.workspace = true
sos-sync.workspace = true
sos-server-storage = { workspace = true, features = ["full"] }
sos-logs.workspace = true
sos-protocol = { workspace = true, features = ["files"] }
sos-cli-helpers.workspace = true
sos-signer.workspace = true
sos-vfs.workspace = true

tokio-util.workspace = true
thiserror.workspace = true
tracing.workspace = true
tracing-subscriber.workspace = true
async-trait.workspace = true
http.workspace = true
serde_json.workspace = true
serde.workspace = true
uuid.workspace = true
hex.workspace = true
url.workspace = true
futures.workspace = true
bs58.workspace = true
indexmap.workspace = true
colored.workspace = true
binary-stream.workspace = true
toml.workspace = true 
clap.workspace = true
k256.workspace = true
sha2.workspace = true

axum-server.workspace = true
tokio-rustls.workspace = true
rustls.workspace = true

axum = { version = "0.8", features = ["ws", "original-uri"] }
axum-extra = {version = "0.10", features = ["typed-header"] }
# axum-macros = { version = "0.4" }
axum-prometheus = { version = "0.8", optional = true }
tower-http = { version = "0.6", features = ["cors", "trace"] }
tokio-stream = { version = "0.1" }
utoipa = { version = "5", features = ["uuid"] }
utoipa-rapidoc = { version = "5", features = ["axum"] }
tokio = { version = "1", features = ["rt", "rt-multi-thread", "sync", "macros"] }
tokio-rustls-acme = { version = "0.6", features = ["axum"], optional = true }

[build-dependencies]
rustc_version = "0.4.1"
