use thiserror::Error;

/// Errors generated by the audit library.
#[derive(Debug, Error)]
pub enum Error {
    /// Error generated when attempting to append audit
    /// events without any providers configured.
    #[error("no audit trail providers configured")]
    AuditProvidersNotConfigured,

    /// Error generated by the IO module.
    #[error(transparent)]
    Io(#[from] std::io::Error),

    /// Error generated by the core library.
    #[error(transparent)]
    Core(#[from] sos_core::Error),

    /// Error generated by the filesystem library.
    #[error(transparent)]
    FileSystem(#[from] sos_filesystem::Error),
}
