[package]
name = "sos-client-storage"
version = "0.16.0"
edition = "2021"
description = "Client storage for the Save Our Secrets SDK."
homepage = "https://saveoursecrets.com"
license = "MIT OR Apache-2.0"
repository = "https://github.com/saveoursecrets/sdk"

[features]
full = ["audit", "files", "archive", "search"]
archive = ["sos-filesystem/archive"]
audit = ["sos-audit", "sos-backend/audit"]
files = [
  "sos-external-files",
  "sos-sync/files",
  "sos-reducers/files",
  "dep:tokio-util",
  "dep:age",
  "dep:binary-stream",
]
search = [
  "sos-search",
]

[dependencies]
sos-core.workspace = true
sos-backend.workspace = true
sos-database.workspace = true
sos-password.workspace = true
sos-filesystem.workspace = true
sos-login.workspace = true
sos-reducers.workspace = true
sos-signer.workspace = true
sos-sync.workspace = true
sos-vault.workspace = true
sos-vfs.workspace = true

sos-external-files = { workspace = true, optional = true }
sos-search = { workspace = true, optional = true }
sos-audit = { workspace = true, optional = true }

thiserror.workspace = true
tracing.workspace = true
tokio.workspace = true
indexmap.workspace = true
uuid.workspace = true
async-trait.workspace = true
secrecy.workspace = true
sha2.workspace = true
serde.workspace = true
futures.workspace = true
hex.workspace = true
parking_lot.workspace = true

binary-stream = { workspace = true, optional = true }
tokio-util = { workspace = true, optional = true }
age  = { workspace = true, optional = true }

[build-dependencies]
rustc_version.workspace = true
