[package]
name = "sos-client-storage"
version = "0.16.0"
edition = "2021"
description = "Client storage for the Save Our Secrets SDK."
homepage = "https://saveoursecrets.com"
license = "MIT OR Apache-2.0"
repository = "https://github.com/saveoursecrets/sdk"

[features]
full = ["audit", "files", "archive", "search"]
archive = ["sos-backup-archive"]
audit = ["sos-audit"]
files = [
  "sos-sdk/files",
  "sos-sync/files",
  "dep:tokio-util",
  "dep:age",
  "dep:binary-stream",
]
search = [
  "sos-backend/search",
  # "dep:probly-search",
  # "dep:unicode-segmentation",
  # "dep:url",
  # "dep:vcard4",
]

[dependencies]
sos-core.workspace = true
sos-backend.workspace = true
sos-database.workspace = true
sos-password.workspace = true
sos-filesystem.workspace = true
sos-signer.workspace = true
sos-sync.workspace = true
sos-sdk.workspace = true
sos-vault.workspace = true
sos-vfs.workspace = true

sos-search = { workspace = true, optional = true }
sos-audit = { workspace = true, optional = true }
sos-backup-archive = { workspace = true, optional = true }

thiserror.workspace = true
tracing.workspace = true
tokio.workspace = true
indexmap.workspace = true
uuid.workspace = true
async-trait.workspace = true
secrecy.workspace = true
sha2.workspace = true
serde.workspace = true
futures.workspace = true
hex.workspace = true

binary-stream = { workspace = true, optional = true }
tokio-util = { workspace = true, optional = true }
age  = { workspace = true, optional = true }

# search
# unicode-segmentation = { workspace = true, optional = true }
# probly-search = { workspace = true, optional = true }
# url  = { workspace = true, optional = true }
# vcard4 = { workspace = true, optional = true }

[build-dependencies]
rustc_version.workspace = true
