use thiserror::Error;

/// Errors generated by the library.
#[derive(Debug, Error)]
pub enum Error {
    /// Errors generated by the IO module.
    #[error(transparent)]
    Io(#[from] std::io::Error),

    /// Errors generated by the JSON library.
    #[error(transparent)]
    Json(#[from] serde_json::Error),

    /// Errors generated by the backend library.
    #[error(transparent)]
    Backend(#[from] sos_backend::Error),

    /// Errors generated by the client storage library.
    #[error(transparent)]
    ClientStorage(#[from] sos_client_storage::Error),

    /// Errors generated by the archive library.
    #[error(transparent)]
    Archive(#[from] sos_archive::Error),
}
