name: Homebrew

on: [pull_request]

#on:
  #workflow_call:

jobs:
  homebrew:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Set environment variables
        run: |
          VERSION=$(cargo pkgid | cut -f2 -d '@')
          DOMAIN="https://releases.saveoursecrets.com"

          curl -OL $DOMAIN/cli/macos/$VERSION/aarch64/saveoursecrets.zip.sha256.txt
          ARM_SHA=$(cat saveoursecrets.zip.sha256.txt)

          curl -OL $DOMAIN/cli/macos/$VERSION/x86_64/saveoursecrets.zip.sha256.txt
          X86_SHA=$(cat saveoursecrets.zip.sha256.txt)

          echo "SEMVER=$VERSION"  >> $GITHUB_ENV
          echo "ARM_SHA=$ARM_SHA" >> $GITHUB_ENV
          echo "X86_SHA=$X86_SHA" >> $GITHUB_ENV

      - uses: actions/checkout@v3
        with:
          repository: 'saveoursecrets/homebrew-sos'
          path: '.homebrew'

      - name: Execute homebrew build.sh
        run: |
          echo $SEMVER
          echo $ARM_SHA
          echo $X86_SHA

          cd .homebrew
          git checkout -b "v$SEMVER"

          VERSION=$SEMVER \
            ARM_SHA=$ARM_SHA \
            X86_SHA=$X86_SHA \
            ./build.sh

          cp -f sos-build.rb Formula/sos.rb

          git config --local user.email "homebrew-release-bot@noreply.saveoursecrets.com"
          git config --local user.name "homebrew-release[bot]"

          git add Formula/sos.rb
          git commit -a -m "Update formula for $SEMVER release."

          git branch

      - name: Push changes
        uses: ad-m/github-push-action@master
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          directory: '.homebrew'
          branch: 'v${{ env.SEMVER }}'

      - name: Create Pull Request
        uses: peter-evans/create-pull-request@v5
        with:
          path: '.homebrew'
          title: 'Update release to ${{ env.SEMVER }}'
          branch: 'v${{ env.SEMVER }}'
