name: Release

on:
  push:
    tags:
      - '*'

env:
  RUST_LOG: "0"

jobs:
  build:
    name: build
    strategy:
      fail-fast: false
      matrix:
        settings:
          - host: macos-latest
            target: 'x86_64-apple-darwin'
          - host: windows-latest
            target: 'x86_64-pc-windows-msvc'
          - host: ubuntu-latest
            target: 'x86_64-unknown-linux-gnu'
    runs-on: ${{ matrix.settings.host }}

    steps:
      - uses: actions/checkout@v2
      - name: Install Rust
        uses: actions-rs/toolchain@v1
        with:
          profile: minimal
      - name: Run cargo build
        run: cargo build --release --all --target=${{ matrix.settings.target }}
      - name: Run release artifacts
        run: TARGET=${{ matrix.settings.target }} make release-artifacts
      - uses: actions/upload-artifact@v3
        with:
          name: release-artifacts
          path: target/*.tar.gz

  #upload-release:
    #name: upload-release
    #runs-on: ubuntu-latest
    #needs:
      #- build
    #steps:
      #- uses: actions/checkout@v2
      #- uses: ncipollo/release-action@v1
        #with:
          #artifactErrorsFailBuild: true
          #artifacts: "target/*.tar.gz"
          ##bodyFile: "body.md"
          #token: ${{ secrets.GITHUB_TOKEN }}
