name: Release Artifacts

on:
  push:
    tags:
      - "v*.*.*"

env:
  RELEASE_BUCKET: ${{ vars.RELEASE_BUCKET }} 
  RELEASE_REGION: ${{ vars.RELEASE_REGION }}
  CHANNEL: ${{ vars.DISTRIBUTION_CHANNEL }}

jobs:
  publish:
    uses: ./.github/workflows/publish.yaml
    secrets: inherit

  homebrew:
    uses: ./.github/workflows/homebrew.yaml
    secrets: inherit

  release-artifacts:
    #if: ${{ false }}
    runs-on: ubuntu-latest
    needs:
      - publish
      - homebrew
    steps:
      - uses: actions/checkout@v3
      - name: Set environment variables
        run: |
          VERSION=$(cargo pkgid | cut -f2 -d '@')
          echo "SEMVER=$VERSION" >> $GITHUB_ENV
      - name: Fetch release signing key
        run: |
          curl -OL https://releases.saveoursecrets.com/signing-key.pub
      - name: Install cosign
        uses: sigstore/cosign-installer@v3.1.1
      - name: Check cosign install
        run: cosign version
      - name: Install release tools
        uses: jaxxstorm/action-install-gh-release@v1.10.0
        with:
          token: ${{ secrets.GH_RELEASE_DOWNLOAD }}
          repo: saveoursecrets/release-tools
          platform: 'linux'
          arch: 'x86_64'
      - name: Download artifacts
        env:
          AWS_REGION: ${{ env.RELEASE_REGION }}
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_RELEASE_ACCESS_KEY }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_RELEASE_SECRET_ACCESS_KEY }}
        run: |
          mkdir -p target/artifacts
          release-artifact download \
            --bucket $RELEASE_BUCKET \
            --directory target/artifacts \
            $CHANNEL/cli/linux/$SEMVER/x86_64/saveoursecrets.zip \
            $CHANNEL/cli/linux/$SEMVER/x86_64/musl/saveoursecrets.zip \
            $CHANNEL/cli/windows/$SEMVER/x86_64/saveoursecrets.zip \
            $CHANNEL/cli/macos/$SEMVER/x86_64/saveoursecrets.zip \
            $CHANNEL/cli/macos/$SEMVER/aarch64/saveoursecrets.zip
      - name: Release
        uses: softprops/action-gh-release@v1
        with:
          generate_release_notes: true
          files: |
            target/artifacts/*
            LICENSE
            COPYRIGHT
