name: Release

on:
  push:
    tags:
      - '*'

env:
  RUST_LOG: "0"

jobs:
  build:
    name: build
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Install Rust
        uses: actions-rs/toolchain@v1
        with:
          profile: minimal
      - name: Run cargo build
        run: cargo build --release --all
